### ISSUE TITLE
Wallet is already running error

### ISSUE THREAD

**Issue by ghost** [ipbc-dev/ipbc-wallet#11]
Every time I try to start the wallet I get IPBC wallet already running. This happens after a fresh reboot. The wallet is definitely not running.

**Comment by ghost** [comment]
I was able to figure out the issue. This error happens when you store the blockchain data on a separate hard drive and use a symbolic link that ends up breaking to point to the new directory.

**Comment by ipbc-dev** [comment]
fixed
