### ISSUE TITLE
Getting system error

### ISSUE THREAD

**Issue by vojcha** [ipbc-dev/ipbc-wallet#4]
Hello,

I downloaded the latest release of the wallet but i get this system error when double click on ipbc wallet icon.
![image](https://user-images.githubusercontent.com/36165316/36903467-173f7a9e-1e2e-11e8-957d-28e61cb7c23d.png)

**Comment by ipbc-dev** [comment]
Hello,

you need Visual C++ Redistributable für Visual Studio 2015/2017 https://www.microsoft.com/de-de/download/details.aspx?id=48145

**Comment by ipbc-dev** [comment]
Done
