### ISSUE TITLE
CMake Error at CMakeLists.txt:39 (find_package):   By not providing "FindQt5Gui.cmake" in CMAKE_MODULE_PATH this project has   asked CMake to find a package configuration file provided by "Qt5Gui", but   CMake did not find one.

### ISSUE THREAD

**Issue by NINGPOOL1** [ipbc-dev/ipbc-wallet#5]
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindQt5Gui.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Gui", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Gui" with any
  of the following names:

    Qt5GuiConfig.cmake
    qt5gui-config.cmake

  Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set
  "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by chinf** [comment]
As per the error message, we need to have the Qt5 dev files installed. On my Ubuntu system I tried installing the package "qtbase5-dev" first and this worked for me.

The README.md needs to have this dependency added.
