### ISSUE TITLE
1.1.0.0 release source code yields version 1.0.6

### ISSUE THREAD

**Issue by l1cash** [ipbc-dev/ipbc-wallet#8]
Compiling from either the master branch (as of commit 2f6889a) or the source code zip (provided at https://github.com/ipbc-dev/ipbc-wallet/releases/tag/1.1.0.0) produces a wallet labelled with version 1.0.6.

CryptoNoteWallet.cmake sets CN_VERSION to 1.0.6.

src/cryptonotewallet.rc includes:
#define VER_FILEVERSION             1,0,6,0
#define VER_FILEVERSION_STR         "1.0.6.0\0"
#define VER_PRODUCTVERSION          1,0,6
#define VER_PRODUCTVERSION_STR      "1.0.6\0"

The compiled wallet runs and the GUI shows 1.0.6, but the auto updater doesn't show at all despite http://ftp.ipbc.io/IPBC-Wallet/version.txt reading "1.1.0" as of the time of raising this issue.

**Comment by ipbc-dev** [comment]
We werent pushing the release version configs, we are now.
