### ISSUE TITLE
has too weak proof of work

### ISSUE THREAD

**Issue by eeeeLeeee** [ipbc-dev/ipbc-wallet#9]
2018-Apr-17 00:48:29.197948 INFO    Block 114ddf890af573cc90e09b8ccda1ecf7a72661afab0c0cd51fce9954f901dc09, has too weak proof of work: ab743845d2ef4e330a17a44f2b890efd5df107ae58941c4dbe8d6ab800000000, expected difficulty: 6010344338 MajorVersion: 3

**Comment by ipbc-dev** [comment]
You already put this issue in IPBC earlier.
